name: woutickpass
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # qr_code_scanner: ^1.0.1
  http: ^1.2.1
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.3
  sunmi_scanner: ^0.0.4
  
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
